"""Unified competing routes computation across platforms.

Handles logprobs from:
- Ollama local (top_alternatives as list of dicts)
- Together.ai API (top_logprobs as list of objects)
- Fireworks.ai API (same OpenAI format)
- Any OpenAI-compatible API

Usage:
    from friktionsllm.friction.cr_utils import compute_cr_from_logprobs

    result = client.generate(prompt, logprobs=True)
    cr_stats = compute_cr_from_logprobs(result.token_logprobs)
    print(f"Mean CR: {cr_stats['mean_cr']:.3f}")
"""

from __future__ import annotations

import json
import math
import os
import warnings
from dataclasses import dataclass

# Per-model threshold sidecar lookup. Generated by
# scripts/a2_fit_profile_thresholds.py from real per_token_cr distributions.
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
PROFILE_THRESHOLDS_DIR = os.path.join(_PROJECT_ROOT, "data", "profile_thresholds")
_THRESHOLD_CACHE: dict[str, dict] = {}


# === LEGACY hardcoded thresholds ===
# These thresholds were calibrated against ONE model in the early experiments
# and copy-pasted across 14 scripts. The 2026-04-09 audit (Vej B + A1) showed:
#   - Every model with >30 questions has mean_cr > 2.0, so the legacy
#     `mean_cr < 1.5` test for "LOW" never fires on real data.
#   - The two threshold sets disagreed: 14 scripts used (mean<1.5; std>0.8;
#     pct>50) while CRStats.profile_type used (mean<1.05; std>0.5; pct>30%).
#   - Re-classifying with model-native percentile thresholds shifts buckets
#     dramatically and gave +0.0 to +0.4pp deployable lift on 11/12 models.
# The legacy values are preserved here ONLY as the fallback when no per-model
# sidecar exists. New code should pass `model_id=` to get native thresholds.
LEGACY_THRESHOLDS = {
    "mean_cr_low_max": 1.5,    # mean_cr < this AND max_cr <= 2 -> LOW
    "max_cr_low_max": 2,
    "std_cr_spiky_min": 0.8,   # std_cr > this AND max_cr >= 3 -> SPIKY
    "max_cr_spiky_min": 3,
    "pct_above_1_spread": 50,  # pct(cr > 1) > this -> SPREAD
}


@dataclass
class CRStats:
    """Competing routes statistics for a generation."""
    mean_cr: float
    max_cr: int
    std_cr: float
    pct_high_friction: float  # % tokens with CR >= 2
    n_tokens: int
    per_token_cr: list[int]
    per_token_margin: list[float]

    @property
    def profile_type(self) -> str:
        """DEPRECATED: classify friction profile based on hardcoded CRStats
        thresholds (mean<1.05; std>0.5). The 2026-04-09 audit showed these
        differ from the 14-script hardcoded set (mean<1.5; std>0.8) AND from
        per-model native thresholds. New code should call
        `classify_profile(self.per_token_cr, model_id=...)` instead.
        Kept for backwards compatibility."""
        if self.n_tokens == 0:
            return "UNKNOWN"
        if self.mean_cr < 1.05:
            return "LOW"
        if self.std_cr > 0.5 and self.max_cr >= 3:
            return "SPIKY"
        if self.pct_high_friction > 0.3:
            return "SPREAD"
        return "EVEN"


def _load_thresholds_for(model_id: str) -> dict | None:
    """Look up per-model JSON sidecar at data/profile_thresholds/<model_id>.json.
    Returns None if no sidecar exists. Caches results for the process lifetime."""
    if not model_id:
        return None
    if model_id in _THRESHOLD_CACHE:
        return _THRESHOLD_CACHE[model_id]
    path = os.path.join(PROFILE_THRESHOLDS_DIR, f"{model_id}.json")
    if not os.path.exists(path):
        _THRESHOLD_CACHE[model_id] = None
        return None
    try:
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
    except (OSError, json.JSONDecodeError):
        _THRESHOLD_CACHE[model_id] = None
        return None
    _THRESHOLD_CACHE[model_id] = d
    return d


def _classify_legacy(per_token_cr: list[int]) -> str:
    """Replays the body of the 14 hardcoded `def classify_profile` copies.
    The empty/short branch returns 'SPREAD' to match those scripts (CRStats
    returns 'UNKNOWN' instead — we preserve script semantics here)."""
    if not per_token_cr or len(per_token_cr) < 2:
        return "SPREAD"
    n = len(per_token_cr)
    mean_cr = sum(per_token_cr) / n
    max_cr = max(per_token_cr)
    mean_sq = sum((x - mean_cr) ** 2 for x in per_token_cr) / n
    std_cr = math.sqrt(mean_sq)
    pct_above_1 = sum(1 for x in per_token_cr if x > 1) / n * 100
    if mean_cr < LEGACY_THRESHOLDS["mean_cr_low_max"] and max_cr <= LEGACY_THRESHOLDS["max_cr_low_max"]:
        return "LOW"
    if std_cr > LEGACY_THRESHOLDS["std_cr_spiky_min"] and max_cr >= LEGACY_THRESHOLDS["max_cr_spiky_min"]:
        return "SPIKY"
    if pct_above_1 > LEGACY_THRESHOLDS["pct_above_1_spread"]:
        return "SPREAD"
    return "EVEN"


def _classify_native(per_token_cr: list[int], thr: dict) -> str:
    """Classify with per-model native thresholds (mean p33/p67 + std p67).
    Bucket scheme: SPIKY (std override) > LOW (mean<p33) > SPREAD (mean>=p67) > EVEN."""
    if not per_token_cr:
        return "EVEN"
    n = len(per_token_cr)
    mean_cr = sum(per_token_cr) / n
    if n > 1:
        mn = mean_cr
        std_cr = math.sqrt(sum((x - mn) ** 2 for x in per_token_cr) / n)
    else:
        std_cr = 0.0
    mp33 = thr.get("mean_p33")
    mp67 = thr.get("mean_p67")
    sp67 = thr.get("std_p67")
    if sp67 is not None and std_cr >= sp67 and (mp33 is None or mean_cr >= mp33):
        return "SPIKY"
    if mp33 is not None and mean_cr < mp33:
        return "LOW"
    if mp67 is not None and mean_cr >= mp67:
        return "SPREAD"
    return "EVEN"


def classify_profile(
    per_token_cr: list[int],
    *,
    model_id: str | None = None,
    thresholds: dict | None = None,
) -> str:
    """Canonical CR-distribution classifier returning one of LOW/EVEN/SPREAD/SPIKY.

    This is the SINGLE source of truth that replaces the 14 hardcoded
    `classify_profile` copies that lived in scripts/. See the 2026-04-09 audit
    notes in LEGACY_THRESHOLDS above for why those were wrong.

    Resolution order:
      1. If `thresholds` is provided directly (a dict with mean_p33/mean_p67/
         std_p67 keys), use it. This is the call form used by analysis scripts
         that re-fit thresholds in-memory.
      2. Else if `model_id` is provided AND a sidecar at
         data/profile_thresholds/<model_id>.json exists, use it. Generate
         sidecars with scripts/a2_fit_profile_thresholds.py.
      3. Else fall back to LEGACY hardcoded thresholds and emit a one-shot
         DeprecationWarning per process. New code should always pass
         `model_id=` so future re-runs land on per-model thresholds.

    Args:
        per_token_cr: list of per-token competing-routes counts (typically 1..6)
        model_id: profile-key for sidecar lookup (e.g. "qwen3_235b",
            "cogito_671b_full"). Should match the filename of the
            iterative_profile_*.jsonl that produced the data.
        thresholds: dict with mean_p33/mean_p67/std_p67 to use directly.

    Returns:
        One of "LOW", "EVEN", "SPREAD", "SPIKY". (Empty/very-short input
        returns "SPREAD" to match the legacy semantics that callers depend on.)
    """
    if thresholds is not None:
        return _classify_native(per_token_cr, thresholds)
    if model_id:
        thr = _load_thresholds_for(model_id)
        if thr is not None:
            return _classify_native(per_token_cr, thr)
    # Fall through to legacy. Emit a one-shot warning per call site so we
    # eventually move all callers off the deprecated path.
    warnings.warn(
        "classify_profile() called without model_id or thresholds; using "
        "LEGACY hardcoded thresholds (mean<1.5; std>0.8; pct>50). These are "
        "miscalibrated for every model audited on 2026-04-09. Pass "
        "model_id=<key> to use per-model native thresholds (sidecar in "
        "data/profile_thresholds/).",
        DeprecationWarning,
        stacklevel=2,
    )
    return _classify_legacy(per_token_cr)


def extract_probs_from_token(token_data) -> list[float]:
    """Extract all token probabilities from a single token's logprobs.

    Handles multiple formats:
    - Ollama: TokenLogprob with .logprob and .top_alternatives (list of dicts)
    - OpenAI/Together/Fireworks: object with .logprob and .top_logprobs (list of objects)
    - Raw dict format from JSON
    """
    probs = []

    # Get chosen token probability
    if hasattr(token_data, 'logprob'):
        probs.append(math.exp(token_data.logprob))
    elif isinstance(token_data, dict) and 'logprob' in token_data:
        probs.append(math.exp(token_data['logprob']))

    # Get alternative probabilities - try all known formats
    alternatives = None

    # Format 1: Ollama local (.top_alternatives)
    if hasattr(token_data, 'top_alternatives') and token_data.top_alternatives:
        alternatives = token_data.top_alternatives
    # Format 2: OpenAI API (.top_logprobs)
    elif hasattr(token_data, 'top_logprobs') and token_data.top_logprobs:
        alternatives = token_data.top_logprobs
    # Format 3: Dict with top_logprobs key
    elif isinstance(token_data, dict) and 'top_logprobs' in token_data:
        alternatives = token_data['top_logprobs']
    # Format 4: Dict with top_alternatives key
    elif isinstance(token_data, dict) and 'top_alternatives' in token_data:
        alternatives = token_data['top_alternatives']

    if alternatives:
        for alt in alternatives:
            if isinstance(alt, dict):
                if 'logprob' in alt:
                    # OpenAI format: {"token": "x", "logprob": -1.23}
                    probs.append(math.exp(alt['logprob']))
                else:
                    # Ollama format: {"token_text": logprob_value}
                    for _token, lp in alt.items():
                        if isinstance(lp, (int, float)):
                            probs.append(math.exp(lp))
            elif hasattr(alt, 'logprob'):
                # Object with .logprob attribute
                probs.append(math.exp(alt.logprob))

    return probs


def compute_cr_from_logprobs(
    token_logprobs: list,
    *,
    prob_threshold: float = 0.10,
) -> CRStats:
    """Compute competing routes from any logprobs format.

    Args:
        token_logprobs: List of token logprob data (any format)
        prob_threshold: Minimum probability to count as competing (default 10%)

    Returns:
        CRStats with all computed metrics
    """
    per_token_cr = []
    per_token_margin = []

    for token_data in token_logprobs:
        probs = extract_probs_from_token(token_data)

        if not probs:
            continue

        # Count competing routes
        n_competing = sum(1 for p in probs if p > prob_threshold)
        per_token_cr.append(n_competing)

        # Margin between top-1 and top-2
        probs_sorted = sorted(probs, reverse=True)
        if len(probs_sorted) >= 2:
            per_token_margin.append(probs_sorted[0] - probs_sorted[1])

    n_tokens = len(per_token_cr)

    if n_tokens == 0:
        return CRStats(
            mean_cr=1.0, max_cr=1, std_cr=0.0,
            pct_high_friction=0.0, n_tokens=0,
            per_token_cr=[], per_token_margin=[],
        )

    mean_cr = sum(per_token_cr) / n_tokens
    max_cr = max(per_token_cr)
    std_cr = (sum((x - mean_cr) ** 2 for x in per_token_cr) / n_tokens) ** 0.5 if n_tokens > 1 else 0.0
    pct_high = sum(1 for x in per_token_cr if x >= 2) / n_tokens

    return CRStats(
        mean_cr=mean_cr,
        max_cr=max_cr,
        std_cr=std_cr,
        pct_high_friction=pct_high,
        n_tokens=n_tokens,
        per_token_cr=per_token_cr,
        per_token_margin=per_token_margin,
    )
